### ISSUE TITLE
HACS repository

### ISSUE THREAD

**Issue by Philantrop** [PaarthShah/matrix-nio-hacs#3]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/PaarthShah/matrix-nio-hacs/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I've manually cloned the repository and moved everything in place but that's inconvenient for most and impossible for many potential users.

### Describe the solution you'd like

Since your upstream merge request seems to be going nowhere, please consider creating a HACS repository which is a great solution for everyone.

### Describe alternatives you've considered

Short of bribing a Homeassistant dev to review your MR? None.

### Additional context

-

**Comment by Philantrop** [comment]
Sorry, mistake: Adding this repository's URL as a custom repository in HACS works just fine. You might want to make something like *that* your installation instructions and keep the manual instructions as a fallback.

**Comment by PaarthShah** [comment]
Glad that the HACS custom URL worked as intended!
But yeah, I left a lot of things unchanged from the original https://github.com/ludeeus/integration_blueprint template repository that I made this from, so there's plenty of good cleanup to be done regarding this: I appreciate the callout!

**Comment by PaarthShah** [comment]
New https://github.com/PaarthShah/matrix-nio-hacs/blob/16c52f25a054532332419dd3d863c3b8dc8bbb0e/README.md should hopefully make it more clear how to go through the preferred vs custom installation process

**Comment by Philantrop** [comment]
Yes, that's perfect now, thanks!
