### ISSUE TITLE
Push it to mainline Hass from HACS

### ISSUE THREAD

**Issue by kisst** [PaarthShah/matrix-nio-hacs#37]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/PaarthShah/matrix-nio-hacs/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

There is a mainline hass matrix integration which also name you as a [codeowner ](https://github.com/home-assistant/core/blob/dev/homeassistant/components/matrix/manifest.json#L4) hence having the nio based Matrix integration in Hass would be a cleaner solution, then having hacs

### Describe the solution you'd like

See https://community.home-assistant.io/t/change-libraries-for-matrix-chat-to-support-e2e-encryption/211399

### Describe alternatives you've considered

remove default integration and install hacs version instead

### Additional context

-

**Comment by PaarthShah** [comment]
Fixed by: https://github.com/home-assistant/core/pull/72797
